name = "MathOptVRP"
uuid = "ee161a15-0030-435c-8c62-bd8c501c3551"
version = "0.1.0"
authors = ["Benoît Legat <benoit.legat@gmail.com>"]

[deps]
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[weakdeps]
ORTools = "b7d69b34-a827-4671-8cfa-f7e1eec930c7"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[extensions]
MathOptVRPORToolsExt = "ORTools"
MathOptVRPTestExt = "Test"

[compat]
JuMP = "1.31"
MathOptInterface = "1"
ORTools = "0.1"
Random = "1"
Test = "1"
julia = "1.10"
